### ISSUE TITLE
android 9 mate pro 20 connect server fail     log detail under:

### ISSUE THREAD

**Issue by panliaoming** [SheHuan/WanAndroid#1]
11-12 15:14:12.638 23498-26913/com.shehuan.wanandroid D/OkHttp: --> GET http://www.wanandroid.com/banner/json
    --> END GET
11-12 15:14:12.638 23498-26912/com.shehuan.wanandroid D/OkHttp: --> GET http://www.wanandroid.com/article/list/0/json
    --> END GET
11-12 15:14:12.648 23498-26912/com.shehuan.wanandroid D/OkHttp: <-- HTTP FAILED: java.net.UnknownServiceException: CLEARTEXT communication to www.wanandroid.com not permitted by network security policy
11-12 15:14:12.649 23498-26913/com.shehuan.wanandroid D/OkHttp: <-- HTTP FAILED: java.net.UnknownServiceException: CLEARTEXT communication to www.wanandroid.com not permitted by network security policy

**Comment by shehuan** [comment]
应该是这个原因 https://blog.csdn.net/qq_18620851/article/details/80617549
